Description: >
  Oreofeoluwapo Olutola Udacity Challenge 2
  This template deploys a VPC, with a single public and private subnet.
  It deploys an IGW (Internet Gateway) with default route on the public subnet.
  It deploys a NAT Gateway in the public subnet for the private subnet.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to the resource names
    Type: String

  VpcCIDR:
    Description: IP Range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Description: IP Range (CIDR notation) for the public subnet
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnetCIDR:
    Description: IP Range (CIDR notation) for the private subnet
    Type: String
    Default: 10.0.2.0/24

Resources:
  VPC:
    Type: AWS::EC2:VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnabledDnsHostnames: true,
      Tags:
        -Key: Name
         Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2:InternetGteway
    Properties:
      Tags:
        -Key: Name
         Value: !Sub ${EnvironmentName} IGW

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      Tags:
        InternetGatewayId: !Ref InternetGateway
        VpcId: !Ref VPC

  PublicSubnet:
    Type: AWS::EC2:Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet

  PrivateSubnet:
    Type: AWS:EC2:Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet

  NatGatewayElasticIP:
    Type: AWS::EC2::EIP
    DependsOn: IGWAttachment
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayElasticIP.AllowcationId
      SubnetId: !Ref PublicSubnet
